services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: airq

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend

    container_name: air-backend

    restart: always

    env_file:
      - backend/.env

    depends_on:
      - mysql

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend

      args:
        VITE_API_URL: http://15.206.109.45:8000

    container_name: air-frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  mysql_data:
